openapi: 3.0.3
info:
  version: 1.0.0
  title: Flowchase API
  description: >
    Flowchase API, a RESTful API for the Flowchase performance tool
  termsOfService: "https://www.flowchase.app/terms"
  license:
    name: proprietary software
    url: "https://www.flowchase.app/license"
  x-logo:
    url: "https://storage.googleapis.com/flwc-app-media/flowchaseapilogo.png"
paths:
  $ref: src/domains/performance-tool/router.yaml#/router

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    feedback:
      type: object
      description: The feedback object
      properties:
        word:
          type: string
        wordIndex:
          type: number
        wordPriority:
          type: number
        feedbackPriorities:
          type: object
          properties:
            total:
              type: number
        feedbackPriority:
          type: number
        status:
          type: string
          enum: [success, failure]
        feedback:
          type: array
          items:
            $ref: "#/components/schemas/feedbackCard"
        ipa:
          type: string
        start:
          type: number
        end:
          type: number

    feedbackCard:
      type: object
      description: The feedback card object
      properties:
        order:
          type: number
        type:
          type: string
        status:
          type: string
          enum: [success, failure]
        aspect:
          type: string
        message:
          type: string
        image:
          type: string
        priority:
          type: number
        metadata:
          type: object

security:
  - api_key: []
servers:
  - url: "https://api-staging.flowchase.app"
